name: Update Sports Ticker

on:
  schedule:
    - cron: '0 16 * * *'  # ✅ 6:00 AM HST (daily)
    - cron: '0 9 * * *'   # ✅ 11:00 PM HST (daily)
  workflow_dispatch:      # ✅ allows manual testing too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch cheerio

      - name: Run scraper script
        run: node updateTicker.js

      - name: Commit updated ticker file
        run: |
          git config user.name "OlomanaBot"
          git config user.email "bot@olomana.org"
          git add hhsaa_ticker.json
          git commit -m "update: auto-refresh HHSAA ticker"
          git push
